import { Plus_Jakarta_Sans, DM_Sans, Yesteryear } from 'next/font/google'

import "/public/assets/css/app.css"
import "/public/assets/css/magnific-popup.css"
import "/public/assets/css/jquery.fancybox.min.css"
import "/public/assets/css/textanimation.css"

const jakarta = Plus_Jakarta_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--font-Jakarta",
    display: 'swap',
})
const dM_Sans = DM_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--font-dm",
    display: 'swap',
})
const yesteryear = Yesteryear({
    weight: [ '400'],
    subsets: ['latin'],
    variable: "--font-Yesteryear",
    display: 'swap',
})
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${jakarta.variable} ${dM_Sans.variable} ${yesteryear.variable} body header-fixed` }>{children}</body>
        </html>
    )
}
